name: abk_env

on:
  push:
  pull_request:

jobs:
  MacOS:
    name: MacOS ${{ matrix.version }}
    runs-on: macos-${{ matrix.version }}
    strategy:
      matrix:
        version: [14, 15]
    steps:
      - uses: actions/checkout@v4

      - name: Ensure correct SHELL availability
        run: cat /etc/shells

      - name: Run tool install/uninstall in bash
        shell: bash
        run: |
          export SHELL=$(which bash)
          echo "SHELL = $SHELL"
          echo "USER_SHELL = $USER_SHELL"
          ./pipeline_test.sh

      - name: Run tool install/uninstall in zsh
        shell: zsh
        run: |
          export SHELL=$(which zsh)
          echo "SHELL = $SHELL"
          echo "USER_SHELL = $USER_SHELL"
          ./pipeline_test.sh

  Ubuntu:
    name: Ubuntu ${{ matrix.version }}
    runs-on: ubuntu-${{ matrix.version }}
    strategy:
      matrix:
        version: [22.04, 24.04]
    steps:
      - uses: actions/checkout@v4

      - name: Ensure correct SHELL availability
        run: cat /etc/shells

      - name: Run tool install/uninstall in bash
        shell: bash
        run: |
          export SHELL=$(which bash)
          echo "SHELL = $SHELL"
          echo "USER_SHELL = $USER_SHELL"
          ./pipeline_test.sh

      - name: Run tool install/uninstall in zsh
        shell: zsh
        run: |
          export SHELL=$(which zsh)
          echo "SHELL = $SHELL"
          echo "USER_SHELL = $USER_SHELL"
          ./pipeline_test.sh


#   Docker:
#     name: Linux Docker - ${{ matrix.os }}:${{ matrix.version }}
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         include:
#           - os: debian
#             version: "9"
#           - os: debian
#             version: "10"
#           - os: debian
#             version: "11"
#           - os: debian
#             version: "12"
#           - os: raspbian
#             version: "9"
#           - os: raspbian
#             version: "10"
#           - os: raspbian
#             version: "11"
#           - os: raspbian
#             version: "12"
#           - os: ubuntu
#             version: "20.10"
#           - os: ubuntu
#             version: "22.10"
#           - os: ubuntu
#             version: "24.04"
#     steps:
#       - uses: actions/checkout@v4
#       - name: Run tool install/uninstall tests in Docker
#         run: |
#           docker pull ${{ matrix.os }}:${{ matrix.version }}
#           docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace ${{ matrix.os }}:${{ matrix.version }} /bin/bash -c "
#             apt-get update && apt-get install -y bash sudo curl gnupg
#             ./test-install.sh
#             ./test-uninstall.sh
#           "
